# Generated by Django 5.2.1 on 2025-05-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgraduateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postgraduate_courses', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='UndergraduateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergraduate_courses', to='core.course')),
            ],
        ),
    ]
