# Generated by Django 5.2.1 on 2025-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_undergraduatecourse_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_semesters',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price_per_semester',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='years_to_complete',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
