# Generated by Django 5.2.1 on 2025-05-30 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_course_number_of_semesters_course_price_per_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
                ('photo', models.ImageField(upload_to='students/photos/')),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('local_address', models.CharField(blank=True, max_length=255, null=True)),
                ('gov_id', models.FileField(upload_to='students/gov_ids/')),
                ('passport_visa', models.FileField(blank=True, null=True, upload_to='students/passport_visa/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='students/birth_certificates/')),
                ('nationality_proof', models.FileField(blank=True, null=True, upload_to='students/nationality_proof/')),
                ('marksheet_10', models.FileField(upload_to='students/marksheets/', verbose_name='Class 10 Mark Sheet')),
                ('marksheet_12', models.FileField(upload_to='students/marksheets/', verbose_name='Class 12 Mark Sheet')),
                ('grad_marksheet', models.FileField(blank=True, null=True, upload_to='students/marksheets/')),
                ('tc', models.FileField(blank=True, null=True, upload_to='students/tc/')),
                ('migration', models.FileField(blank=True, null=True, upload_to='students/migration/')),
                ('abc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('language_proof', models.FileField(blank=True, null=True, upload_to='students/language_proof/')),
                ('caste_certificate', models.FileField(blank=True, null=True, upload_to='students/caste_certificate/')),
                ('domicile', models.FileField(blank=True, null=True, upload_to='students/domicile/')),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='students/income_certificate/')),
                ('disability_certificate', models.FileField(blank=True, null=True, upload_to='students/disability_certificate/')),
                ('entrance_score', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_type', models.CharField(choices=[('Regular', 'Regular'), ('Distance', 'Distance'), ('International', 'International')], max_length=20)),
                ('portal_login', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_receipt', models.FileField(blank=True, null=True, upload_to='students/fee_receipt/')),
                ('medical_fitness', models.FileField(blank=True, null=True, upload_to='students/medical_fitness/')),
                ('vaccination', models.FileField(blank=True, null=True, upload_to='students/vaccination/')),
                ('parent_details', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=128)),
                ('temp_password', models.CharField(blank=True, help_text='Temporary password to be changed by the student', max_length=128, null=True)),
                ('batch_from', models.PositiveIntegerField(verbose_name='Batch Year (From)')),
                ('batch_to', models.PositiveIntegerField(verbose_name='Batch Year (To)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.country')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.course')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.state')),
            ],
        ),
    ]
